<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6144e955-fc1a-4f19-84df-42f17bab2e0a</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/aside[1]/div[1]/div[1]/nav[1]/ul[1]/li[6]/ul[1]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>